//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.MyIOOperations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyIOOperations.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApplication1.MyIOOperations.HelloWorldResponse HelloWorld(WindowsFormsApplication1.MyIOOperations.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name contents from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SnedFile", ReplyAction="*")]
        WindowsFormsApplication1.MyIOOperations.SnedFileResponse SnedFile(WindowsFormsApplication1.MyIOOperations.SnedFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.MyIOOperations.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApplication1.MyIOOperations.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.MyIOOperations.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApplication1.MyIOOperations.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SnedFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SnedFile", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.MyIOOperations.SnedFileRequestBody Body;
        
        public SnedFileRequest() {
        }
        
        public SnedFileRequest(WindowsFormsApplication1.MyIOOperations.SnedFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SnedFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] contents;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public SnedFileRequestBody() {
        }
        
        public SnedFileRequestBody(byte[] contents, string fileName) {
            this.contents = contents;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SnedFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SnedFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.MyIOOperations.SnedFileResponseBody Body;
        
        public SnedFileResponse() {
        }
        
        public SnedFileResponse(WindowsFormsApplication1.MyIOOperations.SnedFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SnedFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SnedFileResult;
        
        public SnedFileResponseBody() {
        }
        
        public SnedFileResponseBody(string SnedFileResult) {
            this.SnedFileResult = SnedFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : WindowsFormsApplication1.MyIOOperations.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.MyIOOperations.ServiceSoap>, WindowsFormsApplication1.MyIOOperations.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.MyIOOperations.HelloWorldResponse WindowsFormsApplication1.MyIOOperations.ServiceSoap.HelloWorld(WindowsFormsApplication1.MyIOOperations.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApplication1.MyIOOperations.HelloWorldRequest inValue = new WindowsFormsApplication1.MyIOOperations.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.MyIOOperations.HelloWorldRequestBody();
            WindowsFormsApplication1.MyIOOperations.HelloWorldResponse retVal = ((WindowsFormsApplication1.MyIOOperations.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.MyIOOperations.SnedFileResponse WindowsFormsApplication1.MyIOOperations.ServiceSoap.SnedFile(WindowsFormsApplication1.MyIOOperations.SnedFileRequest request) {
            return base.Channel.SnedFile(request);
        }
        
        public string SnedFile(byte[] contents, string fileName) {
            WindowsFormsApplication1.MyIOOperations.SnedFileRequest inValue = new WindowsFormsApplication1.MyIOOperations.SnedFileRequest();
            inValue.Body = new WindowsFormsApplication1.MyIOOperations.SnedFileRequestBody();
            inValue.Body.contents = contents;
            inValue.Body.fileName = fileName;
            WindowsFormsApplication1.MyIOOperations.SnedFileResponse retVal = ((WindowsFormsApplication1.MyIOOperations.ServiceSoap)(this)).SnedFile(inValue);
            return retVal.Body.SnedFileResult;
        }
    }
}
